### ISSUE TITLE
Starlink init scripts should not set DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by smaret** [Starlink/starlink#1]
On MacOS Starlink init scripts (starlink.login and starlink.sh) set the DYLD_LIBRARY_PATH variable to point to Starlink installed libraries. This causes problems for programs installed with [Fink](http://www.finkproject.org). For example, Fink's Python version uses version 8.5.0 of TK library, which is installed under /sw/lib. If one set the DYLD_LIBRARY_PATH to include /star/lib in the path, Python attempts to use the TK version under /star/lib, and it crashes if the version is older than the one it was compiled with.

Indeed, if the binaries are linked properly, one should not need to set this variable, because the executable contains the full path to libraries.

**Comment by sfgraves** [comment]
Assuming nobody is going to be able to fix-up the build system to do this before the next  Starlink release in Mid march, I'm going to see if I can implement the script that fixes up the paths afterwards.

After a very brief look for some info  on paths on Mac and install_name_tool, I think I'll need a script that does:

1) add an rpath to the cfitisio .dylibs on the mac install. This will prevent DYLD_LIBRARY_PATH from needing to be set. 

We'd need to use install_name_tool -id to change the path in the .dylibs to be relative to the starlink top-level directory.

Then use install_name_tool -add-rpath on each binary that links to cfitisio with the relative path to the libcitsio.dylib (using either \@loader_path or \@executable_path I guess?), And then use install_name_tool -change to use the @rpath  in the binary.

2) If we want to make the MacOSX build relocatable, we'd need to have a script that repeats the same procedure on all the .dylibs and all the binaries. 

( would this cause problems with libjpeg issues in issue #26 ?)

I'm going to see if I can get this working first for cfitisio.

**Comment by sfgraves** [comment]
I've commited a post-makeworld script (macos_postbuild_library_fixup.sh in commit c506e0155df4c13c8784ae01a94) that attempts to fixup all the binaries and dylibs shipped under $STARLINK_DIR/lib and $STARLINK_DIR/bin so that:

a) all dylibs have an id that uses @ rpath
b) all the libraries that any dylib or binary attempts to load are at paths relative to the @ rpath
c) all dylibs and libraries have their  relative path to $STARLINK_DIR added as an rpath

This still requires testing, but if it works then this issue can be closed and DYLD_LIBRARY_PATH won't be required after running the script. It should also make the build relocatable.

**Comment by sfgraves** [comment]
The 2015A OSX release that we just shipped used the post-build fix up scripts to add rpaths to all the libraries and copy in missing dependency libraries (e.g. gfortran) that we don't build. It therefore does not set DYLD_LIBRARY_PATH.

Is there any hope of fixing up the build process to set the rpaths properly in the near future, or shall we continue using the post-build solution?

If we're going to use this post-build solution for a while I'd like to make it a little more automated (i.e. I had to hand edit the profile/login/cshrc scripts) and describe it properly in the README file.

**Comment by timj** [comment]
Fixing the build system is beyond my autoconf abilities. If @pwdraper had a Mac then we'd probably have it working by now :smile:

I'm getting a bit wound up by the JPEG issue. We should never build our own JPEG library on the Mac as it's always possible to use the system ImageIO framework. The trick is teaching configure that that is an option.

**Comment by sfgraves** [comment]
@grahambell  did recently buy a book on autoconf, but I don't think he wants to do much that's OSX specific...

Do you know if the libJPEG shipped in the ImageIO framework will 'just work' if  we try and build against it -- i.e. if we could get the autoconf system to pass the -framework ImageIO flag to the compiler would our code all build and work without changes, or would we have to re-write any of the actual code?
