### ISSUE TITLE
Change URLs of links Starlink documents

### ISSUE THREAD

**Issue by MalcolmCurrie** [Starlink/starlink#44]
As I was adding an old link to SC/20, it reminded me that we need to
switch jach.hawaii.edu links to the new eaobservatory.org in our
documents at a suitable date.

**Comment by timj** [comment]
Links to Starlink should still use http://www.starlink.ac.uk -- Links to JAC pages need to be replaced with EAO links.

**Comment by grahambell** [comment]
Done in commits bc46053fbc97ba6aab767d6592ee57e80f297ce7 through 587476ca69f9646371147b9ced7c6ead11e1d4f8.
