### ISSUE TITLE
Rename githib organisation from JACH to EAO

### ISSUE THREAD

**Issue by dsberry** [Starlink/starlink#46]
Presumably at some point we need to change all references to JACH on github, to be EAO. See https://help.github.com/articles/renaming-an-organization/

Could be quite a fragile process....

**Comment by sfgraves** [comment]
Did you mean to file this against starlink, or against one of the jac-h repos? (I think the starlink repo is part of the Starlink organisation, so shouldn't need changing)

**Comment by timj** [comment]
I assume @dsberry was mentioning it here because the Starlink repo will need to be updated to point to the new locations of the submodules.

My personal preference is to leave jac-h as it is and create a new eao organization. Not all the repos in jac-h are of interest to eao. You also won't want the same admins. I'd vote for only moving code to the new org that is actively being worked on by EAO and leave the older stuff behind in jac-h.

**Comment by grahambell** [comment]
Not really a Starlink issue.  Anyway I spoke with CAW about this this morning and will be renaming the jac-h organization and removing the non-EAO employees shortly.

**Comment by timj** [comment]
Please don't do that. Please create a NEW organization. What do I do with all my old JAC repos that are not actively supported by EAO?

**Comment by grahambell** [comment]
Which repositories under "jac-h" do you mean?

**Comment by timj** [comment]
At the moment it's jcmt_coadd, linked from the ASCL entry.

**Comment by grahambell** [comment]
Renaming an organization is supposed to cause references to the repositories to be redirected, so it shouldn't cause any problems immediately.  I don't see why jcmt_coadd couldn't be in the new organization -- after all EAO is supposed to be maintaining all the data in the archive so we ought to have the software.

**Comment by grahambell** [comment]
Renaming an organization is supposed to cause references to the repositories to be redirected, so it shouldn't cause any problems immediately.  I don't see why jcmt_coadd couldn't be in the new organization -- after all EAO is supposed to be maintaining all the data in the archive so we ought to have the software.

**Comment by timj** [comment]
How does git know after you clone the repo that the .gitmodules are all in a different place? Does github store a redirect so even though you use the jac-h url it is redirected to eao?

Yes, you could support the jcmt_coadd repo, it's just that I would lose push access at that point...

**Comment by grahambell** [comment]
Yes GitHub is supposed to redirect the tracking URLs, according to this page:

    https://help.github.com/articles/what-happens-when-i-change-my-organization-s-name/

We can then grant specific access to jcmt_coadd, can't we?
