### ISSUE TITLE
No frog in profile

### ISSUE THREAD

**Issue by grahambell** [Starlink/starlink#48]
etc/init/profile.in doesn't create an alias for frog, whereas cshrc.in does.

(Problem found testing 2015A-RC2 but probably not necessary to fix for the 2015A release.)

**Comment by timj** [comment]
Mainly because frog never actually got released properly and the bash support for Starlink was added much later.

**Comment by grahambell** [comment]
Corrected in commit 803f6dd64b7e0d0af903c317921461b3cba1560a.
