### ISSUE TITLE
./build-modules.sh fails at LWP::Protocol:https

### ISSUE THREAD

**Issue by sfgraves** [Starlink/starlink#49]
The build-modules script to install extra perl modules regularly fails when installing the LWP::protocol::https package. This a is a dependency needed when installing Astro-Catalog-4.31, so this problem is only encountered when installing into a new build.

The error message written into the log is:
```
#   Failed test at t/apache.t line 18.
#                   'Can't connect to www.apache.org:443 (certificate verify failed)
#
# LWP::Protocol::https::Socket: SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at /net/kamaka/export/data/star/star-legacy-r1/star-2015A/Perl/lib/perl5/site_perl/5.18.2/LWP/P\
rotocol/http.pm line 47.
# '
#     doesn't match '(?^:Apache Software Foundation)'
```

The work around is to manually install that dependency using --force to ignore the test results, and then re-run the build-modules script again.

Should this be behaviour be included in the build-modules script (as is done with the Tk module already)? Or is there a better way to avoid getting that error message which I've missed? This problem occurs both on Mac and on Linux, at least when building in Hilo.

**Comment by timj** [comment]
Looks like a problem with the SSL verification. Maybe a transient issue because of all the recent SSL updates.

**Comment by sfgraves** [comment]
I'd have assumed so, except I've run into this issue quite a few times before (quite a few times over at least the last year). If its transient then I have the absolute worst luck in running into it.

**Comment by sfgraves** [comment]
Closing, as this problem hasn't occurred again in the last few months.
