### ISSUE TITLE
Gaia interface issue when loading non-existant file

### ISSUE THREAD

**Issue by sfgraves** [Starlink/starlink#50]
Reported by one of the JCMT support scientists:

If you run gaia with a non existent file name, you have to click 'Okay' on two identical boxes telling you that the file doesn't exist, instead of just on one. You can't interact with gaia until you've clicked 'Okay' on both boxes.

(To add to the inconsistency: If you use gaiadisp, the gaiadisp script actually checks if the file exists and puts a message on the command line instead of using a dialogue box indicating the file was not there. )

@pwdraper Any interest in fixing it? I don't think it was super urgent, it was just irritating them a little.

**Comment by pwdraper** [comment]
I had a look at this a while back (think Malcolm mentioned it to me) and it turns out to be a 
tricky little problem with event timing and the interface between GAIA and Skycat. I'll have
another look.

**Comment by pwdraper** [comment]
I've committed a fix f515b87. That works, but I'm concerned there may be some side-effects,
so give it a run through your system.

**Comment by sfgraves** [comment]
Anything specific you want me to look out for? Our automated nightly builds will be done by this afternoon, so I can check with those if you just need a check on another system. I'm also probably going to update our /stardev build here in Hilo pretty soon, so hopefully we'll hear back fairly promptly from the support scientists if anything causes issues.

**Comment by pwdraper** [comment]
The main things to look out for are badly parsed names (unlikely, since it passes the
tests I'd tried), and incorrectly placed images (positioning and zoom). The actual load
of the data is now delayed, so timing issues are the most likely.

**Comment by sfgraves** [comment]
This fix seems to be working fine now. Thanks Peter!
