### ISSUE TITLE
pamela not being initialised correctly in bash

### ISSUE THREAD

**Issue by trmrsh** [Starlink/starlink#63]
Having set up starlink under bash for the first time as opposed to tcsh, I have found a tiny but show-stopping bug. "type pamela" returns:

pamela is a function
pamela () 
{ 
    ${PAMELA_DIR}/pamela.sh
}

whereas "type figaro" says

figaro is a function
figaro () 
{ 
    . $FIG_DIR/figaro.sh
}

The crucial point is the lack of the initial '. ' in the pamela case which means the file "pamela.sh" does not get sourced, it gets run, so all the command definitions it contains are lost. I believe that this should be correctable by inserting the leading '. ' at the appropriate point in file etc/init/profile.in

I would be happy to do so and 'git push' it but I thought I would raise it as an issue since I could have misunderstood how things work.

**Comment by grahambell** [comment]
I added the missing '.' to the profile.in file in commit 6d99cbc381b9ea8d9ca8a5120a2ee87757344b1c.
