### ISSUE TITLE
GAIA cannot move to any directories

### ISSUE THREAD

**Issue by jeffreyrdcs** [Starlink/starlink#64]
Hi, I am using the 2018A version of GAIA on MacOSX.   The GUI starts without problems. 
However the select file popup does not allow one to move to other directories.  It gives the following error:

Error: unmatched open brace in list
unmatched open brace in list
    while executing
"foreach i [exec /bin/ls -a $itk_option(-dir)] {
           catch {
              if {[file isdirectory $i]} {
                 if {$itk_option(-full)}..."
    (object "::.gaia1.select" method "::util::FileSelect::_filldirlist" body line 3)
    invoked from within
"_filldirlist"
    (object "::.gaia1.select" method "::util::FileSelect::_filtercmd" body line 20)
    invoked from within
"::.gaia1.select _filtercmd"
    (in namespace inscope "::util::FileSelect" script line 1)
    invoked from within
"namespace inscope ::util::FileSelect {::.gaia1.select _filtercmd}"
    invoked from within
".gaia1.select.fs.btnf.ff.f invoke"
    (command bound to event)

**Comment by pwdraper** [comment]
Hi, don't have a Mac I can try this out on (could someone with a Mac try a simple check that
this isn't badly broken in the release, the source files involved have not been modified, so I suspect not,
all is OK under Linux), anyway, so just guessing, but I suspect that you probably have
some usual names for either files or directories that GAIA is attempting to list.

If that doesn't make sense send the output from: `gaia -debuglog 1`, i.e. the file `GaiaDebug.log`
so I can see more detail.

**Comment by jeffreyrdcs** [comment]
Thanks for the quick reply.  I have attached a screenshot and the debug logfile. 
I suspect it is not a filename issue since I could not even move to any directories.  I am using macOS Mojave if someone can try if the issue is related to the OS version.

[GaiaDebug.log](https://github.com/Starlink/starlink/files/3118356/GaiaDebug.log)

![gaia_screenshot](https://user-images.githubusercontent.com/10601455/56759390-b64aaa00-674d-11e9-9d15-0d88f732d234.png)

**Comment by sfgraves** [comment]
To confirm, Gaia on my OSX mojave machine using Star 2018A has no problem moving between directories. I tried making a few test directories with spaces in them and braces and had no problems with those either. 

Peter may be able to tell more from the debug log.


One possible test would be to make a new directory tree with nothing in it for testing purposes?
e.g.
mkdir /Users/chanjeffrey/Desktop/testGaia1
mkdir /Users/chanjeffrey/Desktop/testGaia1/testGaiaSub

Then do

cd /Users/chanjeffrey/Desktop/testGaia1
gaia 

And see if you can move between the testGaia1 and the testGaia1/testGaiaSub directories?

**Comment by jeffreyrdcs** [comment]
That works!  I dug a bit more - turns out Peter was right.  It is due to some of the randomly generated files I had on my desktop having "{" as the first character of their file names.  

Thanks Sarah and Peter!

**Comment by pwdraper** [comment]
Just out of curiosity I think the file was `{ .jpg`. Good to hear it was something easy to fix.
(As you may have guessed `{` is a very special character in the scripts that make up GAIA).
