### ISSUE TITLE
pamela polfit command not found

### ISSUE THREAD

**Issue by htugcas** [Starlink/starlink#68]
polfit and various other commands are not found in bash (MasOS High Sierra 10.13.6) despite the following files exist.

pamela folder is under star-2018A/bin, and inside pamela there is polfit and many others. 

profile file in star-2018A/etc has pamela as

```
#  PAMELA

if test -f ${bindir}/pamela/pamela.sh; then
   export PAMELA_DIR=${bindir}/pamela
fi
```
Am I missing something or is there a discrepancy?

**Comment by trmrsh** [comment]
Hi, yes, I think this comes down to the following lines within $STARLINK_DIR/etc/profile:

if test -f ${bindir}/pamela/pamela.sh; then
   pamela () { ${PAMELA_DIR}/pamela.sh; }
   pamelasetup () { ${PAMELA_DIR}/pamela.sh; }
else

which should instead be:

if test -f ${bindir}/pamela/pamela.sh; then
   pamela () { . ${PAMELA_DIR}/pamela.sh; }
   pamelasetup () { . ${PAMELA_DIR}/pamela.sh; }
else

I thought I had corrected this (post-2018A) on github but I lack the competence to be sure of this and could not see anything obvious when I ran 'git log'.

**Comment by htugcas** [comment]
I have read this solution and already checked it but apparently I had to ask to sort it out. Thanks a million!

**Comment by timj** [comment]
Looks like @grahambell fixed it in commit 6d99cbc381b9ea8d9ca8a5120a2ee87757344b1c a year ago so it looks like a 2019 release should be fine.

**Comment by htugcas** [comment]
I used the latest release [here.](http://starlink.eao.hawaii.edu/starlink/Releases)  If there is a new release in 2019, this page might benefit an update.

**Comment by sfgraves** [comment]
We (EAO) didn't do a release in 2019 -- 2018A is the most recent. We do provide nightly builds from the master branch on github though.

We're planning a release in early 2020, but I'm not sure exactly when. I'm hoping we can get some decent testing on David's changes to a C-based NDF and to support 64 bit indexing, so that might delay it a bit.
