### ISSUE TITLE
Plan for XML documentation

### ISSUE THREAD

**Issue by timj** [Starlink/starlink#7]
Starlink has a few documents that were written in XML rather than LaTeX. These documents use a completely different build system and rely on components that are no longer supported (e.g. Jade). Currently they are not installed and not included in the updates to the build system when fixing #4.

#5 has some comments from @nxg and @MalcolmCurrie concerning the XML documentation.

The documents have some useful information so the issue is what we do with them? One option is to indicate that the documents are frozen and generate PDF versions that are installed without attempting to do an automated build. This would seem to be the pragmatic solution. Certainly less work than attempting to rejig the build using modern tools.

**Comment by grahambell** [comment]
I converted SC/13 as discussed above in commit 4c6f99b26a6bdf66c4dd8071cdbe6e2710a8d043.

**Comment by sfgraves** [comment]
SSN/78 has been converted to latex in commit a382d8608eab9466 

Graham suggested earlier today that anything still current in SUN/248 should be noted in the README file (which has effectively replaced it, and already has much of the relevant information). After that, SUN/248 could be obsoleted.

**Comment by sfgraves** [comment]
Having taken a quick look at SUN/248, I think all of the information in it can be classed as either included or superseded by information in the README. I'm going to move this to obsolete. Any references to SUN/248 in the existing code should be updated to point readers towards the README. (If anyone thinks I missed anything useful, please add it to the README file.)

**Comment by timj** [comment]
And after that you can move `applications/sgmlkit` to obsolete as well and disable `dvi2bitmap`.

**Comment by sfgraves** [comment]
This was done in commits 8ebeefbd3f76882e (sgmlkit) and 1f57baba024047b95580cd (dvi2bitmap)

**Comment by timj** [comment]
I think this means the issue is closed. Thanks.
